### ISSUE TITLE
Symmetry definition

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DLR-boeh-da/CPACS#394]
```
Check the symmetry information in CPACS. Probably the documentation needs to be 
updated. 
```

Original issue reported on code.google.com by `boehni...@gmail.com` on 15 Sep 2014 at 9:03

**Comment by DLR-boeh-da** [comment]
Three references are possible for a symmetric component: 
- compete component (e.g. whole wing)
- defined component (e.g. right wing)
- symmetric component (e.g. left wing)

The current definition in CPACS is not sufficient to reference all three elements. Hence, the following naming conventions is proposed:

Definition Component
<wing uID=„mainWing“ symmetry =„x-z-plane“>

References to component
- Whole wing uID = „mainWing“
- Defined wing uID = „mainWing_symm“
- Symmetric wing uID = „mainWing_mirror“

Please note, this is not downward compatible...

**Comment by DLR-boeh-da** [comment]
Carsten added some valuable comments to the discussion. Will shortly include them here: 

- No clear definition is available on whether parts will be duplicated via symmetry, e.g. VTP on the BWB. Carsten proposes to exclude this option
- _def and _sym instead of the options proposed above
- Symmetric component shall be defined up to the symmetry plane
- Linked components, e.g. engines on a wing, shall not be copied as a result of the symmetry. 
- Need to take into account symmetry and guidecurves

**Comment by DLR-boeh-da** [comment]
We discussed the issue at the FrEACs Meeting in Hamburg 2015. The proposed solution is to add an symmetry attribute to the stringUIDBaseType. The optional argument may have the values: full, symm or def. Hence if one references to a part he may specify whether the whole part is meant or only one half. 

<parentUID isLink="True" symmetry="def">wingUID</parentUID>
