### ISSUE TITLE
CPACS 3.5 Release feature list: fuel replacement

### ISSUE THREAD

**Issue by FaRunge** [DLR-boeh-da/CPACS#835]
According to the CPACS 3.5 feature list https://github.com/DLR-SL/CPACS/releases/tag/v3.5 "fuels [have been] replaced by chemicalEnergyCarriers and electricalEnergyCarriers."

This is also mentioned here https://github.com/DLR-SL/CPACS/issues/606 and this picture is also given:
![image](https://github.com/DLR-SL/CPACS/assets/173960761/d759c2a6-6f7b-42d3-8aea-f2f0bccb6313)

I fail to find `chemicalEnergyCarriers `and `electricalEnergyCarriers` in Version 3.5. Instead I find `fuels`, as you can see in the following image. However, as the feature list states, I shouldn't actually be able to find fuels because it is said to be replaced.
![image](https://github.com/DLR-SL/CPACS/assets/173960761/b8cf1752-15b2-41e4-8520-e8f669b126d4)

I am new to CPACS. Am I missing something here?

**Comment by MarAlder** [comment]
The change did not make it through the final review process. We have decided to continue naming `chemicalEnergyCarriers` as `fuel` in order to remain consistent with other nodes in CPACS. The electrical energy carriers have not yet been worked out in detail, which is why they are planned for the next release.

Thanks for the hint, I will adjust the 3.5 feature list again.

**Comment by FaRunge** [comment]
Thanks for the reply. Is there a rough date for the next release?

**Comment by MarAlder** [comment]
Difficult to say, it is a high priority, but no date has been set yet.
